### PR TITLE
Make package installable from pip

### PR DESCRIPTION
**Pull request by neishm**
Includes the source for `librmn-016.2`, `vgrid-6.4.b2`, `libburpc-1.9`, and the `armnlib` headers which are needed for installing outside the CMC/science environments.

Can either use `pip install` on a local copy of the repository, or as @jeixav pointed out to me, can be installed from the remote git repository.  For instance, to install from this GitHub branch:
```
pip install git+https://github.com/neishm/python-rpn.git@pip-install
```
Requires `gfortran >= 4.9.4` and and the `perl-uri` package for doing the installation this way.

Should also work for the intel compiler if you set the environment variables `CC=icc` and `FC=ifort`.

### CODE REVIEW

**Comment by neishm** [comment]
Moved the source codes for `librmn`, `vgrid`, and `libburpc` out of this repository, and instead reference the source repositories as optional submodules.

As a result, under normal circumstances the shared libraries will not be compiled, and running `python setup.py install` or `pip install .` on a python-rpn working directory will simply install the Python modules and scripts.  I think this is more in-line with what's expected for development work.

Now, the shared libraries will only be compiled and bundled under specific circumstances, such as:

1. Running `pip install` on a remote git repository of python-rpn,  or
2. If the submodules are explicitly loaded into the git working directory (e.g. by running `git submodule update --init`, or cloning the repo with the `--recursive` option).

**Comment by meteokid** [comment]
This looks good, great work! Thanks Michael.

Is there anyway the include files from librmn and the patches could be put elsewhere?  
Looks like these are meant to be part of the actual librmn, vgrid and burpc repositories.  
I know that librmn and vgrid will be changing quite a bit in the near future. Having patches and copies on the RPNpy side would make it hard to keep up.

**Comment by neishm** [comment]
I could move the whole `src/` directory into a separate repository and link as a submodule so it's out of the way.  It's not needed for day-to-day stuff anyway.

**Comment by neishm** [comment]
The include files and patches have now been moved outside this repository.  They're still available as an optional submodule by running `git submodule update --init --recursive`, but they won't appear under normal circumstances when cloning / pushing / pulling / etc.

**Comment by meteokid** [comment]
Sounds good. Thanks!  
I'll have a closer look asap and merge it in.

**Comment by neishm** [comment]
Is there an easy way to tell from this repository which versions of librmn, vgrid, and libburp were used for the SSM packages?  So far I'm basing the optional shared library compilation on information gleamed from the commit messages (e.g. 3e6477b412932ea4dbe667f9c1d6b49324657094), but I can't see where these versions are actually set...

Thanks,
Mike

**Comment by meteokid** [comment]
> Is there an easy way to tell from this repository which versions of librmn, vgrid, and libburp were used for the SSM packages? 

I guess this info is no longer avail in this repos, it was moved to another repos (migdep) shared with other in-house products; that new repos is not yet made avail thus not linked here.

That being said, I'm not sure why this matters since these libs are mostly static, at least on the API front. Thus you should be able to use the latest versions without any need to change the python-rpn code.

**Comment by neishm** [comment]
The main reason was to get consistent library versions regardless of whether the package was loaded on the science network or built outside the network.  If the APIs are mostly static, though, then it should be sufficient for me to periodically check the public repositories for newer library versions and update accordingly.

**Comment by neishm** [comment]
Maybe I should split this pull request into two separate pieces - the part that adds a `setup.py` script for doing simple installations on systems where the libraries are already available, then a second part that allows the shared libraries to be built and installed alongside the python-rpn scripts.  The title and intention of this pull request is a little ambiguous right now...

**Comment by neishm** [comment]
The first part has been been cleaned up and redone as #26.  The second part will be revisited later.

**Pull request closed without merging**
